# *******************************************************************************************
# *******************************************************************************************
#
#      Name :      Makefile
#      Purpose :   Makefile wrapper.
#      Date :      2nd July 2025
#      Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

include ../../environment/system.make
APPNAME = input
include $(BUILDENVDIR)pico.$(OS).make

locales:
	make -B -C ../../other/data/localisation all